[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.2"
  NPM_VERSION = "10.2.4"

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "https://your-backend-url.onrender.com/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200