[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.2"
  NPM_VERSION = "10.2.4"

[dev]
  command = "npm run dev"
  port = 5174

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
