services:
  - type: web
    name: AMGS CRM-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # You'll need to set these in Render's dashboard
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false

# If you need a database in the future, uncomment this section:
# databases:
#   - name: postgres_db
#     databaseName: my_AMGS CRM_db
#     user: my_AMGS CRM_user